class PowerlineSymbols < Formula
  desc "PowerlineSymbols.otf for powerline."
  homepage "https://github.com/powerline/fonts"

  url "https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf"
  sha256 "4a2496a009b1649878ce067a7ec2aed9f79656c90136971e1dba00766515f7a1"
  version "20151204.0"
  revision 2

  depends_on "fontconfig" => :build

  def fonts_conf_xml(path)
    <<~EOS
    <?xml version="1.0"?>
    <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
    <!-- /etc/fonts/fonts.conf file to configure system font access -->
    <fontconfig>
      <its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
        <its:translateRule translate="no" selector="/fontconfig/*[not(self::description)]"/>
      </its:rules>

      <description>Default configuration file</description>

    <!--
        DO NOT EDIT THIS FILE.
        IT WILL BE REPLACED WHEN FONTCONFIG IS UPDATED.
        LOCAL CHANGES BELONG IN 'local.conf'.

        The intent of this standard configuration file is to be adequate for
        most environments.  If you have a reasonably normal environment and
        have found problems with this configuration, they are probably
        things that others will also want fixed.  Please submit any
        problems to the fontconfig bugzilla system located at fontconfig.org

        Note that the normal 'make install' procedure for fontconfig is to
        replace any existing fonts.conf file with the new version.  Place
        any local customizations in local.conf which this file references.

        Keith Packard
    -->

    <!-- Font directory list -->
        <dir>#{path}</dir>
    </fontconfig>
    EOS
  end

  def install
    fontpath = share/"fonts/Homebrew/powerline-symbols"
    fontpath.mkpath

    conf = etc/"fonts/conf.d/55-homebrew-powerline-symbols.conf"
    conf.delete if conf.exist?

    fontpath.install "./PowerlineSymbols.otf"

    conf.write(fonts_conf_xml(opt_share/"fonts"))
  end

  def caveats; <<~EOS
    If you want to use Truetype font `Koruri`, as follows make a symbolic link
    in directory /usr/share/fonts or $HOME/.local/share/fonts, and run `fc-cache`
    command.
    
      # cd /usr/share/fonts
      # ln -sf #{ENV["HOMEBREW_PREFIX"]}/share/fonts/Homebrew .
      # fc-cache -vf
      
      or
      
      $ cd $HOME/.local/share/fonts/Homebrew
      $ ln -sf #{ENV["HOMEBREW_PREFIX"]}/share/fonts/Homebrew .
      $ fc-cache -fv
    EOS
  end

  def post_install
    system "#{Formula["fontconfig"].opt_bin}/fc-cache", "-vf"
  end

  test do
    system "#{Formula["fontconfig"].opt_bin}/fc-list"
  end
end
